In [20]:
animals= ['Tiger', 'Elephant', 'Lion']
a, b, c= animals
print(a)
print(b)
print(animals[2])

Tiger
Elephant
Lion


In [21]:
print (a+b)

TigerElephant


In [28]:
print (a + b)

SyntaxError: unexpected character after line continuation character (Temp/ipykernel_7944/95734149.py, line 1)

In [54]:
a ='Orange'
def afunc():
    global a
    a = 'Apple'
    print (a)
afunc()
#print(a)

Apple


In [19]:
import numpy as np
a= np.array([[1,2,3] , [4,5,6]])
print(a.ndim)

2


In [9]:
np.arange(1,6,3)

array([1, 4])

In [12]:
np.linspace(1,5,7)

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        ])

In [20]:
np.full((3,4,2),1)

array([[[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]])

In [36]:
b=np.arange(1,20,2)
c=b.reshape(10) #without the first number or the row value it takes "1" as default
print(c)

[ 1  3  5  7  9 11 13 15 17 19]


In [8]:
a=1267543675485778943624577547687985768767957878
id(a)

2294350280480

In [6]:
import math
a= 8.8
math.ceil(a)

9

In [51]:
import numpy
array_1 = numpy.array([[1,2,3],[0,7,12]]) 
array_2 = numpy.array([[0,0,0],[7,8,9]]) 
print(numpy.concatenate((array_1, array_2), axis = 1))


[[ 1  2  3  0  0  0]
 [ 0  7 12  7  8  9]]


In [26]:
a=[*range(1,11,1)]
a_sq=[i**2 for i in a]
print(a_sq)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [60]:
def year(a):
    if (a%4 == 0): print ('The year: {} is leap year'.format(a));
    else: print(f'The Year: {a} Not a leap year!'); 
year(2005)

The Year: 2005 Not a leap year!
